name: lead_plugin_epoint
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  auto_size_text_plus: ^3.0.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0
  file_picker: ^9.2.0
  keyboard_actions: ^4.2.0
  image: ^4.5.3
  rxdart: ^0.28.0
  webview_flutter: ^4.10.0
  flutter_widget_from_html: ^0.16.0
  mime: ^2.0.0
  aws_s3_upload_lite: ^0.1.6
  connectivity_plus: ^6.1.3
  path: ^1.9.1
  flutter_direct_call_plus: ^0.0.3
  image_picker_android: ^0.8.12+22
  video_player_android: ^2.8.2

dependency_overrides:
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.lead_plugin_epoint
        pluginClass: LeadPluginEpointPlugin
      ios:
        pluginClass: LeadPluginEpointPlugin
      web:
        pluginClass: LeadPluginEpointWeb
        fileName: lead_plugin_epoint_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/languages/
    - assets/icons/
    - assets/images/

